export const FETCH_SELECTED_CITY = "FETCH_SELECTED_CITY";
export const ADD_TO_CITY_LIST = "ADD_TO_CITY_LIST";
export const REMOVE_FROM_CITY_LIST = "REMOVE_FROM_CITY_LIST";
export const CLEAR_CITY_LIST = "CLEAR_CITY_LIST";
